version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/examples/mobile-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/examples/nextjs-webapp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/examples/python-api"
    schedule:
      interval: "weekly"
